name: Keep Render Server Alive

on:
  schedule:
    - cron: "*/3 * * * *" # كل 3 دقائق
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: |
          curl -I https://tarafbackend.onrender.co
